"""empty message

Revision ID: 2b586bd1437e
Revises: 2dad5e9ce9d5
Create Date: 2015-05-08 00:56:26.882106

"""

# revision identifiers, used by Alembic.
revision = '2b586bd1437e'
down_revision = '2dad5e9ce9d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
