"""empty message

Revision ID: 2dad5e9ce9d5
Revises: 3f81a6a0b280
Create Date: 2015-05-08 00:53:02.834474

"""

# revision identifiers, used by Alembic.
revision = '2dad5e9ce9d5'
down_revision = '3f81a6a0b280'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', 'roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
