"""empty message

Revision ID: 373a4df27574
Revises: 431f4e1d7a8a
Create Date: 2015-05-08 02:35:11.240777

"""

# revision identifiers, used by Alembic.
revision = '373a4df27574'
down_revision = '431f4e1d7a8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
